// <auto-generated />
using ApiCSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCSharp.Migrations
{
    [DbContext(typeof(MyAnimesContext))]
    [Migration("20260614074656_RefazendoAsMigration")]
    partial class RefazendoAsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCSharp.Models.Anime", b =>
                {
                    b.Property<int>("MalId")
                        .HasColumnType("int");

                    b.Property<int>("Episodios")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ImagensUrlMal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SubTitulos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MalId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("ApiCSharp.Models.MyAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AnimesMalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MyAnimes");
                });
#pragma warning restore 612, 618
        }
    }
}
