// <auto-generated />
using ApiMusicX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMusicX.Migrations
{
    [DbContext(typeof(MusicContext))]
    partial class MusicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMusicX.Models.ExternalSourceIdentifier", b =>
                {
                    b.Property<long>("ExternalSourceIdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExternalSourceIdentifierId"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("MusicArtistId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicReleaseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicTrackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ExternalSourceIdentifierId");

                    b.HasIndex("MusicArtistId");

                    b.HasIndex("MusicCollectionId");

                    b.HasIndex("MusicReleaseId");

                    b.HasIndex("MusicTrackId");

                    b.HasIndex("Provider", "ResourceType", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalSourceIdentifiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalSourceIdentifiers_ExactlyOneOwner", "(CASE WHEN [MusicArtistId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [MusicCollectionId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [MusicReleaseId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [MusicTrackId] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicArtist", b =>
                {
                    b.Property<long>("MusicArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MusicArtistId"));

                    b.Property<string>("ArtistType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SortName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MusicArtistId");

                    b.HasIndex("NormalizedName");

                    b.ToTable("MusicArtists", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicArtists_ArtistType", "[ArtistType] IN ('Unknown', 'Solo', 'Band', 'Group')");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicArtistAlias", b =>
                {
                    b.Property<long>("MusicArtistAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MusicArtistAliasId"));

                    b.Property<long>("MusicArtistId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MusicArtistAliasId");

                    b.HasIndex("MusicArtistId", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("MusicArtistAliases", (string)null);
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicCollection", b =>
                {
                    b.Property<long>("MusicCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MusicCollectionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MusicCollectionId");

                    b.HasIndex("NormalizedName");

                    b.ToTable("MusicCollections", (string)null);
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicCollectionArtist", b =>
                {
                    b.Property<long>("MusicCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("MusicArtistId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("MusicCollectionId", "MusicArtistId");

                    b.HasIndex("MusicArtistId");

                    b.ToTable("MusicCollectionArtists", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicCollectionArtists_Role", "[Role] IN ('Unknown', 'Primary', 'Member', 'Associated')");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicCollectionRelease", b =>
                {
                    b.Property<long>("MusicCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("MusicReleaseId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("SourceCategory")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("MusicCollectionId", "MusicReleaseId");

                    b.HasIndex("MusicReleaseId");

                    b.ToTable("MusicCollectionReleases", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicCollectionReleases_DisplayOrder", "[DisplayOrder] IS NULL OR [DisplayOrder] >= 0");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicLocalFileReference", b =>
                {
                    b.Property<long>("MusicLocalFileReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MusicLocalFileReferenceId"));

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("MusicReleaseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MusicTrackId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("MusicLocalFileReferenceId");

                    b.HasIndex("MusicReleaseId", "NormalizedPath")
                        .IsUnique()
                        .HasFilter("[MusicTrackId] IS NULL");

                    b.HasIndex("MusicTrackId", "NormalizedPath")
                        .IsUnique()
                        .HasFilter("[MusicTrackId] IS NOT NULL");

                    b.ToTable("MusicLocalFileReferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicLocalFileReferences_RelativePath", "[NormalizedPath] <> '' AND [NormalizedPath] NOT LIKE '/%' AND [NormalizedPath] NOT LIKE '\\\\%' AND [NormalizedPath] NOT LIKE '[A-Za-z]:%' AND [NormalizedPath] NOT LIKE '%..%'");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicRelease", b =>
                {
                    b.Property<long>("MusicReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MusicReleaseId"));

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReleaseType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("MusicReleaseId");

                    b.HasIndex("NormalizedTitle");

                    b.ToTable("MusicReleases", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicReleases_ReleaseType", "[ReleaseType] IN ('Unknown', 'Album', 'Single', 'EP', 'Compilation', 'Video')");

                            t.HasCheckConstraint("CK_MusicReleases_ReleaseYear", "[ReleaseYear] IS NULL OR [ReleaseYear] BETWEEN 1000 AND 9999");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicReleaseArtist", b =>
                {
                    b.Property<long>("MusicReleaseId")
                        .HasColumnType("bigint");

                    b.Property<long>("MusicArtistId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("MusicReleaseId", "MusicArtistId");

                    b.HasIndex("MusicArtistId");

                    b.ToTable("MusicReleaseArtists", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicReleaseArtists_Role", "[Role] IN ('Unknown', 'Primary', 'Featured', 'Composer')");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicTrack", b =>
                {
                    b.Property<long>("MusicTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MusicTrackId"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("DurationText")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("MusicReleaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PositionLabel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("MusicTrackId");

                    b.HasIndex("MusicReleaseId", "PositionLabel", "NormalizedTitle")
                        .IsUnique()
                        .HasFilter("[PositionLabel] IS NOT NULL");

                    b.HasIndex("MusicReleaseId", "Sequence", "NormalizedTitle")
                        .IsUnique()
                        .HasFilter("[Sequence] IS NOT NULL");

                    b.ToTable("MusicTracks", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicTracks_Durations", "([DurationSeconds] IS NULL OR [DurationSeconds] >= 0) AND ([Sequence] IS NULL OR [Sequence] >= 0)");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicTrackArtist", b =>
                {
                    b.Property<long>("MusicTrackId")
                        .HasColumnType("bigint");

                    b.Property<long>("MusicArtistId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("MusicTrackId", "MusicArtistId");

                    b.HasIndex("MusicArtistId");

                    b.ToTable("MusicTrackArtists", null, t =>
                        {
                            t.HasCheckConstraint("CK_MusicTrackArtists_Role", "[Role] IN ('Unknown', 'Primary', 'Featured', 'Composer')");
                        });
                });

            modelBuilder.Entity("ApiMusicX.Models.ExternalSourceIdentifier", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicArtist", "MusicArtist")
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("MusicArtistId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApiMusicX.Models.MusicCollection", "MusicCollection")
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("MusicCollectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApiMusicX.Models.MusicRelease", "MusicRelease")
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("MusicReleaseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApiMusicX.Models.MusicTrack", "MusicTrack")
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MusicArtist");

                    b.Navigation("MusicCollection");

                    b.Navigation("MusicRelease");

                    b.Navigation("MusicTrack");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicArtistAlias", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicArtist", "MusicArtist")
                        .WithMany("Aliases")
                        .HasForeignKey("MusicArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicArtist");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicCollectionArtist", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicArtist", "MusicArtist")
                        .WithMany("CollectionLinks")
                        .HasForeignKey("MusicArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMusicX.Models.MusicCollection", "MusicCollection")
                        .WithMany("ArtistLinks")
                        .HasForeignKey("MusicCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicArtist");

                    b.Navigation("MusicCollection");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicCollectionRelease", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicCollection", "MusicCollection")
                        .WithMany("ReleaseLinks")
                        .HasForeignKey("MusicCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMusicX.Models.MusicRelease", "MusicRelease")
                        .WithMany("CollectionLinks")
                        .HasForeignKey("MusicReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicCollection");

                    b.Navigation("MusicRelease");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicLocalFileReference", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicRelease", "MusicRelease")
                        .WithMany("LocalFileReferences")
                        .HasForeignKey("MusicReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMusicX.Models.MusicTrack", "MusicTrack")
                        .WithMany("LocalFileReferences")
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MusicRelease");

                    b.Navigation("MusicTrack");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicReleaseArtist", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicArtist", "MusicArtist")
                        .WithMany("ReleaseCredits")
                        .HasForeignKey("MusicArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMusicX.Models.MusicRelease", "MusicRelease")
                        .WithMany("ArtistCredits")
                        .HasForeignKey("MusicReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicArtist");

                    b.Navigation("MusicRelease");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicTrack", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicRelease", "MusicRelease")
                        .WithMany("Tracks")
                        .HasForeignKey("MusicReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicRelease");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicTrackArtist", b =>
                {
                    b.HasOne("ApiMusicX.Models.MusicArtist", "MusicArtist")
                        .WithMany("TrackCredits")
                        .HasForeignKey("MusicArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMusicX.Models.MusicTrack", "MusicTrack")
                        .WithMany("ArtistCredits")
                        .HasForeignKey("MusicTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicArtist");

                    b.Navigation("MusicTrack");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicArtist", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("CollectionLinks");

                    b.Navigation("ExternalIdentifiers");

                    b.Navigation("ReleaseCredits");

                    b.Navigation("TrackCredits");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicCollection", b =>
                {
                    b.Navigation("ArtistLinks");

                    b.Navigation("ExternalIdentifiers");

                    b.Navigation("ReleaseLinks");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicRelease", b =>
                {
                    b.Navigation("ArtistCredits");

                    b.Navigation("CollectionLinks");

                    b.Navigation("ExternalIdentifiers");

                    b.Navigation("LocalFileReferences");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ApiMusicX.Models.MusicTrack", b =>
                {
                    b.Navigation("ArtistCredits");

                    b.Navigation("ExternalIdentifiers");

                    b.Navigation("LocalFileReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
