// <auto-generated />
using ApiJikanCSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiJikanCSharp.Migrations
{
    [DbContext(typeof(MyAnimesContext))]
    partial class MyAnimesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiJikanCSharp.Models.Anime", b =>
                {
                    b.Property<int>("MalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MalId"));

                    b.Property<int>("Episodios")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Imagens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MyAnimeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Titles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MalId");

                    b.HasIndex("MyAnimeId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("ApiJikanCSharp.Models.MyAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyAnimes");
                });

            modelBuilder.Entity("ApiJikanCSharp.Models.Anime", b =>
                {
                    b.HasOne("ApiJikanCSharp.Models.MyAnime", null)
                        .WithMany("Animes")
                        .HasForeignKey("MyAnimeId");
                });

            modelBuilder.Entity("ApiJikanCSharp.Models.MyAnime", b =>
                {
                    b.Navigation("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
