// <auto-generated />
using System;
using ApiFileStorage.Monitoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFileStorage.Monitoring.Data.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    partial class MonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.InventoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attributes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastWriteTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Id");

                    b.ToTable("Entries", "monitoring", t =>
                        {
                            t.HasCheckConstraint("CK_Entries_Length", "[LengthBytes] >= 0 AND ([IsDirectory] = 0 OR [LengthBytes] = 0)");
                        });
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Completion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("DirectoryCount")
                        .HasColumnType("bigint");

                    b.Property<long>("FileCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Completion", "FinishedAtUtc", "Id");

                    b.ToTable("Snapshots", "monitoring", t =>
                        {
                            t.HasCheckConstraint("CK_Snapshots_Completion", "[Completion] IN ('Complete', 'Partial', 'Unavailable', 'Cancelled')");

                            t.HasCheckConstraint("CK_Snapshots_Counts", "[FileCount] >= 0 AND [DirectoryCount] >= 0 AND [TotalBytes] >= 0");

                            t.HasCheckConstraint("CK_Snapshots_Times", "[FinishedAtUtc] >= [StartedAtUtc]");
                        });
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.MonitoredLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RootKey");

                    b.ToTable("Locations", "monitoring");
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.MonitoringObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreviousRelativePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Id");

                    b.ToTable("Observations", "monitoring", t =>
                        {
                            t.HasCheckConstraint("CK_Observations_Source", "[Source] IN ('LiveNotification', 'InventoryComparison', 'Monitor')");
                        });
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.InventoryEntry", b =>
                {
                    b.HasOne("ApiFileStorage.Monitoring.Data.InventorySnapshot", null)
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.InventorySnapshot", b =>
                {
                    b.HasOne("ApiFileStorage.Monitoring.Data.MonitoredLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.MonitoringObservation", b =>
                {
                    b.HasOne("ApiFileStorage.Monitoring.Data.MonitoredLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiFileStorage.Monitoring.Data.InventorySnapshot", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
