// <auto-generated />
using System;
using ApiIdentity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiIdentity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260807020126_AddSessionTokens")]
    partial class AddSessionTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiIdentity.Models.IdentityAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("AdultAgeConfirmedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HasConfirmedAdultAge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActivationCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_ActivationState", "([IsActivationCompleted] = 0 AND [ActivatedAtUtc] IS NULL) OR ([IsActivationCompleted] = 1 AND [ActivatedAtUtc] IS NOT NULL AND DATEPART(TZOFFSET, [ActivatedAtUtc]) = 0)");

                            t.HasCheckConstraint("CK_AspNetUsers_AdultAgeConfirmation", "([HasConfirmedAdultAge] = 0 AND [AdultAgeConfirmedAtUtc] IS NULL) OR ([HasConfirmedAdultAge] = 1 AND [AdultAgeConfirmedAtUtc] IS NOT NULL AND DATEPART(TZOFFSET, [AdultAgeConfirmedAtUtc]) = 0)");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityBootstrapState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BootstrappedAccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BootstrappedAccountId");

                    b.ToTable("IdentityBootstrapState", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityBootstrapState_CompletedAtUtc", "DATEPART(TZOFFSET, [CompletedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityBootstrapState_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityProvisioningAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("RetentionUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("RetentionUntilUtc");

                    b.HasIndex("OccurredAtUtc", "Id");

                    b.ToTable("IdentityProvisioningAuditEvents", (string)null);
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityRecoveryTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentityRecoveryTickets_ActiveAccount")
                        .HasFilter("[UsedAtUtc] IS NULL AND [RevokedAtUtc] IS NULL");

                    b.HasIndex("AccountId", "ExpiresAtUtc");

                    b.ToTable("IdentityRecoveryTickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityRecoveryTickets_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityRecoveryTickets_ExpiresAtUtc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityRecoveryTickets_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_IdentityRecoveryTickets_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityRecoveryTickets_UsedAtUtc", "[UsedAtUtc] IS NULL OR DATEPART(TZOFFSET, [UsedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecurityChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Kind", "ExpiresAtUtc");

                    b.ToTable("IdentitySecurityChallenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentitySecurityChallenges_ConsumedAtUtc", "[ConsumedAtUtc] IS NULL OR DATEPART(TZOFFSET, [ConsumedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityChallenges_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityChallenges_ExpiresAtUtc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityChallenges_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_IdentitySecurityChallenges_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecurityDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("TrustedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TrustedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RevokedAtUtc");

                    b.ToTable("IdentitySecurityDevices", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentitySecurityDevices_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityDevices_LastSeenAtUtc", "DATEPART(TZOFFSET, [LastSeenAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityDevices_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityDevices_TrustedAtUtc", "DATEPART(TZOFFSET, [TrustedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityDevices_TrustedUntilUtc", "[TrustedUntilUtc] > [TrustedAtUtc] AND DATEPART(TZOFFSET, [TrustedUntilUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecuritySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "DeviceId");

                    b.HasIndex("AccountId", "RevokedAtUtc");

                    b.ToTable("IdentitySecuritySessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentitySecuritySessions_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecuritySessions_ExpiresAtUtc", "[ExpiresAtUtc] > [CreatedAtUtc] AND DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecuritySessions_LastSeenAtUtc", "DATEPART(TZOFFSET, [LastSeenAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecuritySessions_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecuritySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RestoredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RestoredBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CreatedAtUtc");

                    b.ToTable("IdentitySecuritySnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentitySecuritySnapshots_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecuritySnapshots_ExpiresAtUtc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecuritySnapshots_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_IdentitySecuritySnapshots_RestoredAtUtc", "[RestoredAtUtc] IS NULL OR DATEPART(TZOFFSET, [RestoredAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecuritySnapshots_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecurityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentitySecurityTokens_TokenHash");

                    b.HasIndex("AccountId", "ExpiresAtUtc");

                    b.HasIndex("FamilyId", "RevokedAtUtc");

                    b.HasIndex("SessionId", "RevokedAtUtc");

                    b.ToTable("IdentitySecurityTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentitySecurityTokens_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityTokens_ExpiresAtUtc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityTokens_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_IdentitySecurityTokens_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentitySecurityTokens_TokenType", "[TokenType] IN ('access', 'refresh')");

                            t.HasCheckConstraint("CK_IdentitySecurityTokens_UsedAtUtc", "[UsedAtUtc] IS NULL OR DATEPART(TZOFFSET, [UsedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityStepUpGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Action", "ExpiresAtUtc");

                    b.ToTable("IdentityStepUpGrants", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityStepUpGrants_ExpiresAtUtc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityStepUpGrants_Expiry", "[ExpiresAtUtc] > [GrantedAtUtc]");

                            t.HasCheckConstraint("CK_IdentityStepUpGrants_GrantedAtUtc", "DATEPART(TZOFFSET, [GrantedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityStepUpGrants_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.InitialAccountSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentityInitialAccountSecrets_ActiveAccount")
                        .HasFilter("[UsedAtUtc] IS NULL AND [RevokedAtUtc] IS NULL");

                    b.ToTable("IdentityInitialAccountSecrets", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityInitialAccountSecrets_CreatedAtUtc", "DATEPART(TZOFFSET, [CreatedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityInitialAccountSecrets_ExpiresAtUtc", "DATEPART(TZOFFSET, [ExpiresAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityInitialAccountSecrets_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_IdentityInitialAccountSecrets_RevokedAtUtc", "[RevokedAtUtc] IS NULL OR DATEPART(TZOFFSET, [RevokedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityInitialAccountSecrets_UsedAtUtc", "[UsedAtUtc] IS NULL OR DATEPART(TZOFFSET, [UsedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.PermissionDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Key");

                    b.ToTable("IdentityPermissionDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "catalog.read",
                            Description = "Leitura do catalogo publico."
                        },
                        new
                        {
                            Key = "catalog.write",
                            Description = "Criacao e alteracao do catalogo."
                        },
                        new
                        {
                            Key = "catalog.delete",
                            Description = "Exclusao do catalogo com step-up quando aplicavel."
                        },
                        new
                        {
                            Key = "identity.provision",
                            Description = "Bootstrap e provisionamento administrativo de contas."
                        },
                        new
                        {
                            Key = "identity.login",
                            Description = "Autenticacao no servico de identidade."
                        },
                        new
                        {
                            Key = "identity.self.read",
                            Description = "Leitura do proprio perfil de identidade."
                        },
                        new
                        {
                            Key = "health.read",
                            Description = "Leitura do health minimo restrito."
                        },
                        new
                        {
                            Key = "service.mal.read",
                            Description = "Chamada interna autorizada a dados MyAnimeList."
                        },
                        new
                        {
                            Key = "filesystem.command",
                            Description = "Operacao de arquivos por ID e comando autorizado."
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "PermissionKey");

                    b.HasIndex("PermissionKey");

                    b.ToTable("IdentityRolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "catalog.read"
                        },
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "catalog.write"
                        },
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "catalog.delete"
                        },
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "identity.provision"
                        },
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "identity.self.read"
                        },
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "health.read"
                        },
                        new
                        {
                            RoleId = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            PermissionKey = "filesystem.command"
                        },
                        new
                        {
                            RoleId = "206268dd-529c-49f9-973f-030ddcbba450",
                            PermissionKey = "catalog.read"
                        },
                        new
                        {
                            RoleId = "206268dd-529c-49f9-973f-030ddcbba450",
                            PermissionKey = "identity.self.read"
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.TermsAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TermsDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TermsDocumentId");

                    b.HasIndex("AccountId", "TermsDocumentId")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentityTermsAcceptances_Account_Document");

                    b.ToTable("IdentityTermsAcceptances", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityTermsAcceptances_AcceptedAtUtc", "DATEPART(TZOFFSET, [AcceptedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("ApiIdentity.Models.TermsDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentityTermsDocuments_ActiveType")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("DocumentType", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentityTermsDocuments_Type_Version");

                    b.ToTable("IdentityTermsDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityTermsDocuments_Content", "LEN(LTRIM(RTRIM([Content]))) > 0");

                            t.HasCheckConstraint("CK_IdentityTermsDocuments_ContentHashSha256", "LEN([ContentHashSha256]) = 64 AND [ContentHashSha256] NOT LIKE '%[^0-9A-Fa-f]%'");

                            t.HasCheckConstraint("CK_IdentityTermsDocuments_DocumentType", "LEN(LTRIM(RTRIM([DocumentType]))) > 0");

                            t.HasCheckConstraint("CK_IdentityTermsDocuments_PublishedAtUtc", "DATEPART(TZOFFSET, [PublishedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_IdentityTermsDocuments_Version", "LEN(LTRIM(RTRIM([Version]))) > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            ConcurrencyStamp = "bb9c24e5-6b8a-4464-a420-11db01021681",
                            Name = "Superadministrador",
                            NormalizedName = "SUPERADMINISTRADOR"
                        },
                        new
                        {
                            Id = "206268dd-529c-49f9-973f-030ddcbba450",
                            ConcurrencyStamp = "206268dd-529c-49f9-973f-030ddcbba450",
                            Name = "Usuario do Site",
                            NormalizedName = "USUARIO DO SITE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scopes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityBootstrapState", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "BootstrappedAccount")
                        .WithMany()
                        .HasForeignKey("BootstrappedAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BootstrappedAccount");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityRecoveryTicket", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecurityChallenge", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecurityDevice", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecuritySession", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiIdentity.Models.IdentitySecurityDevice", "Device")
                        .WithMany()
                        .HasForeignKey("AccountId", "DeviceId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecuritySnapshot", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentitySecurityToken", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.IdentityStepUpGrant", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.InitialAccountSecret", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiIdentity.Models.RolePermission", b =>
                {
                    b.HasOne("ApiIdentity.Models.PermissionDefinition", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ApiIdentity.Models.TermsAcceptance", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiIdentity.Models.TermsDocument", "TermsDocument")
                        .WithMany("Acceptances")
                        .HasForeignKey("TermsDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("TermsDocument");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiIdentity.Models.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApiIdentity.Models.IdentityAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("ApiIdentity.Models.PermissionDefinition", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ApiIdentity.Models.TermsDocument", b =>
                {
                    b.Navigation("Acceptances");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
