<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DtudoGateway</AssemblyName>
    <RootNamespace>DtudoGateway</RootNamespace>
    <UserSecretsId>dtudo2026-gateway</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.9" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
  </ItemGroup>

</Project>
